# Generated by Django 3.0.7 on 2020-10-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0042_journal_rename_usager"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="contact_name",
            field=models.TextField(
                default="No contact name provided", verbose_name="Nom du contact"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="contact_email",
            field=models.EmailField(
                default="No contact email provided",
                max_length=254,
                verbose_name="Email du contact",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="status",
            field=models.CharField(
                choices=[
                    ("prospect", "Prospect"),
                    ("onboarded", "Organisation intégrée"),
                ],
                default="onboarded",
                max_length=9,
                verbose_name="Status",
            ),
        ),
    ]
