# Generated by Django 3.0.7 on 2020-11-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0043_organisation_contact_and_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="organisation", name="status",),
    ]
