# Generated by Django 3.0.7 on 2020-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0044_remove_organisation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="datapass_id",
            field=models.IntegerField(
                default=0, verbose_name="ID de la demande Datapass"
            ),
        ),
    ]
