# Generated by Django 3.0.7 on 2020-11-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0045_organisation_datapass_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="siret",
            field=models.BigIntegerField(default=1, verbose_name="N° SIRET"),
        ),
    ]
